### ISSUE TITLE
I did my version for Swift!

### ISSUE THREAD

**Issue by lfarah** [alexruperez/ARAutocompleteTextView#7]
ARAutocompleteTextView.setDefaultAutocompleteDataSource(ARAutocompleteManager.sharedManager())
        let singletap: UITapGestureRecognizer = UITapGestureRecognizer(target: self, action: "handleSingleTap:")
        // Dismiss the keyboard when the user taps outside of a text field
       self.view.addGestureRecognizer(singletap)
        
    }
    func handleSingleTap(recognizer : UIRotationGestureRecognizer)
    {
        self.txtEmail.becomeFirstResponder()
        self.txtEmail.resignFirstResponder()
    }
    
    func textView(textView: UITextView, shouldChangeTextInRange range: NSRange, replacementText text: String) -> Bool {
        if text=="\n"
        {
            self.txtPassword.becomeFirstResponder()
            
            return false
        }
        return true
        
    }

**Comment by alexruperez** [comment]
Nice @lfarah, push it to GitHub! :+1: :)
